// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7SZ3s-BuyZ5xOEeWzBGXHqSppY5rf9vc',
    appId: '1:234310655964:web:7bcf9f0c42a00e92d37919',
    messagingSenderId: '234310655964',
    projectId: 'brew-crew-88205',
    authDomain: 'brew-crew-88205.firebaseapp.com',
    databaseURL: 'https://brew-crew-88205-default-rtdb.firebaseio.com',
    storageBucket: 'brew-crew-88205.firebasestorage.app',
    measurementId: 'G-K0SW8W2CWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZglJ4HIaGSne0bodcyeKV3L-zDYVDqMw',
    appId: '1:234310655964:android:d14229ed89a15deed37919',
    messagingSenderId: '234310655964',
    projectId: 'brew-crew-88205',
    databaseURL: 'https://brew-crew-88205-default-rtdb.firebaseio.com',
    storageBucket: 'brew-crew-88205.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyrQsI3vTxzCFQ5QTXLZIgOxCmQBNf8MI',
    appId: '1:234310655964:ios:e86d1d6a66ea452cd37919',
    messagingSenderId: '234310655964',
    projectId: 'brew-crew-88205',
    databaseURL: 'https://brew-crew-88205-default-rtdb.firebaseio.com',
    storageBucket: 'brew-crew-88205.firebasestorage.app',
    androidClientId: '234310655964-f65j0sqebki4q7pe0kcsiq1d3pd9m3fi.apps.googleusercontent.com',
    iosClientId: '234310655964-km5s6lpvi4389tsd2jbohbdlar9gu30q.apps.googleusercontent.com',
    iosBundleId: 'com.AppMaker.getnowshopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyrQsI3vTxzCFQ5QTXLZIgOxCmQBNf8MI',
    appId: '1:234310655964:ios:e86d1d6a66ea452cd37919',
    messagingSenderId: '234310655964',
    projectId: 'brew-crew-88205',
    databaseURL: 'https://brew-crew-88205-default-rtdb.firebaseio.com',
    storageBucket: 'brew-crew-88205.firebasestorage.app',
    androidClientId: '234310655964-f65j0sqebki4q7pe0kcsiq1d3pd9m3fi.apps.googleusercontent.com',
    iosClientId: '234310655964-km5s6lpvi4389tsd2jbohbdlar9gu30q.apps.googleusercontent.com',
    iosBundleId: 'com.AppMaker.getnowshopapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7SZ3s-BuyZ5xOEeWzBGXHqSppY5rf9vc',
    appId: '1:234310655964:web:1f42a716617c9735d37919',
    messagingSenderId: '234310655964',
    projectId: 'brew-crew-88205',
    authDomain: 'brew-crew-88205.firebaseapp.com',
    databaseURL: 'https://brew-crew-88205-default-rtdb.firebaseio.com',
    storageBucket: 'brew-crew-88205.firebasestorage.app',
    measurementId: 'G-P76TNYF158',
  );

}